---
environment:
  REGISTRY: ${DRONE_REPO_LINK%/$DRONE_REPO}
  IMAGE: ${DRONE_REPO_LINK:8}

trigger:
  event:
    exclude: [promote]

image_pull_secrets: [registry-auth]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: cache
    host:
      path: /tmp/ci-cache

kind: pipeline
type: docker
name: build
concurrency:
  limit: 1

steps:
  - name: build app
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: cache
        path: /root/.cache
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
      - echo $PASSWORD | docker login -u $USERNAME --password-stdin $REGISTRY
      - docker pull $IMAGE:latest || true
      - docker build --cache-from $IMAGE:latest --tag $IMAGE:latest .
      - docker tag $IMAGE:latest $IMAGE:${DRONE_COMMIT_SHA:0:8}
      - docker push $IMAGE:latest
      - docker push $IMAGE:${DRONE_COMMIT_SHA:0:8}
      - |
        if [ -n "${DRONE_TAG}" ]; then
          docker tag $IMAGE:${DRONE_COMMIT_SHA:0:8} $IMAGE:${DRONE_TAG}
          docker push $IMAGE:${DRONE_TAG}
        fi
